import gulp from 'gulp';
import render from 'gulp-nunjucks-render';
import rename from 'gulp-rename';
import handleErrors from '../../lib/handleErrors';
import gutil from 'gulp-util';

export default function (config) {
  return (glyphs) => {
    gutil.log(gutil.colors.blue(`Generating ${config.sassDest}/${config.sassOutputName}`));
    render.nunjucks.configure(config.nunjucks, { watch: false });
    return gulp.src(config.template)
      .pipe(render({
        icons: glyphs.map(glyph => {
          gutil.log(gutil.colors.green(`+ adding ${glyph.name} glyph`));
          return {
            name: glyph.name,
            code: glyph.unicode[0].charCodeAt(0).toString(16).toUpperCase(),
          };
        }),

        fontName: config.options.fontName,
        fontPath: config.fontPath,
        className: config.className,
        comment: `//Generated by gulpfile.js/tasks/iconFont.js\n  //from ${config.template}`,
      }))
    .on('error', handleErrors)
    .pipe(rename(config.sassOutputName))
    .pipe(gulp.dest(config.sassDest));
  };
}
